---
title: "ZIM COVID 19 DASHBOARD"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
library(knitr)
library(data.table)
library(rgdal)
library(sp)
library(DT)
library(rpivotTable)
library(ggplot2)
library(leaflet)
library(sf)
library(grid)
library(tidyverse)
library(IRdisplay)
library(plotly)
library(dplyr)
library(ggpubr)
library(openintro)
library(highcharter)
library(ggvis)
library(corrplot)
library(fontawesome)
```


```{r}

#load shape
base_data <- readOGR("C:\\Users\\AACUser\\Desktop\\Stan\\2.0\\GRAFT\\MScDA\\Assignments\\Visual\\TM_WORLD_BORDERS_SIMPL-0.3",
                     layer="TM_WORLD_BORDERS_SIMPL-0.3",verbose=FALSE)


#Load data
#select world data
base_data@data <- read.csv(file.choose())
data1 = base_data@data


#color palettes
#death
mybins <- c(0,250, 500, 1000, 5000, 10000,50000, 100000, 200000, Inf)
mypalette <- colorBin( palette="YlOrBr", domain=data1$DEATH, na.color="transparent", bins=mybins)

#gdp
mybins1 <- c(0, 250, 500, 1000, 5000, 10000,20000, 50000, 60000)
mypalette1 <- colorBin( palette="Greens", domain=data1$GDP, na.color="transparent", bins=mybins1)


#text popup:
mytext <- paste(
  "Country: ", data1$NAME,"<br/>", 
  "Area: ", data1$AREA, "<br/>",
  "Population: ", data1$POP, "<br/>",
  "Deaths: ", data1$DEATH, "<br/>",
  "Recovery Rate: ", round(data1$RECOVERED / data1$CONFIRMED * 100,1), "%",
  sep="") %>%
  lapply(htmltools::HTML)

#map
m <- leaflet(base_data) %>% 
  addTiles()  %>% 
  setView( lat=-19, lng=30 , zoom=4) %>%
  addPolygons(
    fillColor = ~mypalette(DEATH), 
    stroke=TRUE, 
    fillOpacity = 0.9, 
    color="white", 
    weight=0.3,
    label = mytext,
    group = "Death",
    labelOptions = labelOptions( 
      style = list("font-weight" = "normal", padding = "5px 8px"), 
      textsize = "13px", 
      direction = "auto"
    ),
  ) %>%
  addLegend( pal=mypalette, values=~DEATH, opacity=0.9, title = "COVID Related Deaths ", position = "bottomleft", group = "Death") %>%
  addCircles(lng = ~LON, lat = ~LAT, weight = 1,
             popup = ~NAME, radius = 30000,  group = "GDP", 
             color = ~mypalette1(GDP), fillOpacity = 1) %>%
  addLegend( pal=mypalette1, values=~GDP, opacity=0.9, title = "GDP ", position = "bottomright", group = "GDP" ) %>%
  addLayersControl(overlayGroups = c("Death", "GDP"), 
                 options = layersControlOptions(collapsed = F))

```

Summary
=======================================

Row
---------------------------------------
### COVID 19 Analysis

```{r}
valueBox(paste(""),
         color = "warning")
```

```{r}
#Display values
death.zim <- data1 %>% filter(NAME == "Zimbabwe") %>% select(DEATH)
infected.zim <- data1 %>% filter(NAME == "Zimbabwe") %>% select(CONFIRMED)
recovered.zim <- data1 %>% filter(NAME == "Zimbabwe") %>% select(RECOVERED)

```


### data Effects Analysis

```{r}
valueBox(infected.zim, caption = 'Total Infected', icon = 'fa fa-ambulance')
       
```



### Totally Destroyed
```{r}
library(fontawesome)
valueBox(recovered.zim, caption =  "Total Recoveries", icon = 'fa fa-smile-o')
        
```

### Partially Destroyed

```{r}
valueBox(death.zim, caption =  "Total Fatalities", icon = "fa fa-close")
```


Row
----------------------------------------------------

### Effects by SADC

```{r}
#select SADC COVID
sadc_csv <- read.csv(file.choose(), header = TRUE)
sadc <- as.data.frame(sadc_csv)


#Grouped
ggplot(sadc, aes(fill=Property, y=Value, x=Country)) + 
  geom_bar(position="dodge", stat="identity") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```




### Correlation of Factors

```{r}
trimmed <- data1 %>% select(6:17)
corrplot(cor(trimmed), method = "circle")


```





Map
========================================

### Map

```{r}
#map
m

```


Data Table
========================================

```{r}

data1 %>%
  datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))




```

About Report
========================================
```{r}

tags$h1("Zim COVID-19 Task forces was commissioned to inform the Zimbabwean populace about how the COVID 19 pandamic is
        spreading across the world, and how SADC especially Zimabwe is faring with the fatal disease.  ")

```









